name: Publish package to APK

on:
    release:
    workflow_dispatch:

env:
    REGISTRY: git.oriondev.fr
    PACKAGE_NAME: status
    BRANCH: stable
    REPOSITORY: master

jobs:
    publish:
        runs-on: alpine-latest

        steps:
            - name: Install Node.js and make
              run: apk add --no-cache nodejs make

            - uses: actions/checkout@v4
              name: Checkout

            - uses: actions/setup-go@v6
              name: Setup Go
              with:
                  go-version-file: "go.mod"
                  cache-dependency-path: "go.sum"

            - name: Compile
              run: make compile

            - name: Setting up packaging environment
              run: |
                  apk add alpine-sdk atools doas
                  adduser -G wheel -D user
                  echo "permit nopass :wheel as root" > /etc/doas.d/doas.conf

                  echo 'PACKAGER="orion <contact@oriondev.fr>"' >> /etc/abuild.conf
                  echo 'MAINTAINER="$PACKAGER"' >> /etc/abuild.conf

                  su user -c "abuild-keygen --append --install -n"
                  mkdir -p /home/user/package
                  cp assets/APKBUILD /home/user/package/
                  cp bin/* /home/user/package/
                  chown -R user:user /home/user/package

            - name: Package
              run: |
                  su user -c "cd /home/user/package && abuild checksum && abuild -r"
                  ls /home/user/packages/
